### ISSUE TITLE
Moved from less package to less-autoprefixer does not work

### ISSUE THREAD

**Issue by flemay** [Lauricio/less-autoprefixer#2]
Hi,

I might not understand all the concepts here but I removed the package **less** and added **less-autoprefixer** and the result is not the same.

Basically the layout is as expected with the **less** package but not with **less-autoprefixer**. It looks like it does not compile at all any .less files.
## Env:
- Meteor 1.0.3.2
- MacOSX Yosemite

Any suggestions?

Thanks

**Comment by flemay** [comment]
I've done a new test:

``` bash
$ meteor create test
$ cd test
$ meteor add lauricio:less-autoprefixer
$ mv test.css test.less
$ meteor
```

and got the following error appears:

```
$ meteor
[[[[[ ~/Code/playground/test ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While building the application:
   packages/compileLess/plugin/compile-less.js:48:1: Cannot read
   property 'css' of undefined (compiling test.less)
   at packages/compileLess/plugin/compile-less.js:48:1
   at
   /Users/flemay/.meteor/packages/lauricio_less-autoprefixer/.1.0.15.16pe12z++os+web.browser+web.cordova/plugin.compileLess.os/npm/compileLess/node_modules/less/lib/less/render.js:30:38
   at
...
```

**Comment by msolters** [comment]
**RESOLVED**:
I *had the same exact issue (debug output below)

```
   While building the application:
   <runJavaScript-55>:58:17: Cannot read property 'css' of undefined (compiling
   client/views/navbar/navbar.less)
   at <runJavaScript-55>:58:17
   at
   /home/baron/.meteor/packages/lauricio_less-autoprefixer/.1.0.15.hxcfiq++os+web.browser+web.cordova/plugin.compileLess.os/npm/compileLess/node_modules/less/lib/less/render.js:30:38
   at
   /home/baron/.meteor/packages/lauricio_less-autoprefixer/.1.0.15.hxcfiq++os+web.browser+web.cordova/plugin.compileLess.os/npm/compileLess/node_modules/less/lib/less/parse.js:60:17
   at Object.finish
   (/home/baron/.meteor/packages/lauricio_less-autoprefixer/.1.0.15.hxcfiq++os+web.browser+web.cordova/plugin.compileLess.os/npm/compileLess/node_modules/less/lib/less/parser/parser.js:174:28)
   at Object.ImportVisitor._onSequencerEmpty
   (/home/baron/.meteor/packages/lauricio_less-autoprefixer/.1.0.15.hxcfiq++os+web.browser+web.cordova/plugin.compileLess.os/npm/compileLess/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
   at ImportSequencer.tryRun
   (/home/baron/.meteor/packages/lauricio_less-autoprefixer/.1.0.15.hxcfiq++os+web.browser+web.cordova/plugin.compileLess.os/npm/compileLess/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
   at Object.ImportVisitor.run
   (/home/baron/.meteor/packages/lauricio_less-autoprefixer/.1.0.15.hxcfiq++os+web.browser+web.cordova/plugin.compileLess.os/npm/compileLess/node_modules/less/lib/less/visitors/import-visitor.js:29:25)
   at Object.Parser.parse
   (/home/baron/.meteor/packages/lauricio_less-autoprefixer/.1.0.15.hxcfiq++os+web.browser+web.cordova/plugin.compileLess.os/npm/compileLess/node_modules/less/lib/less/parser/parser.js:180:22)
   at Object.parse
   (/home/baron/.meteor/packages/lauricio_less-autoprefixer/.1.0.15.hxcfiq++os+web.browser+web.cordova/plugin.compileLess.os/npm/compileLess/node_modules/less/lib/less/parse.js:58:18)
   at Object.render
   (/home/baron/.meteor/packages/lauricio_less-autoprefixer/.1.0.15.hxcfiq++os+web.browser+web.cordova/plugin.compileLess.os/npm/compileLess/node_modules/less/lib/less/render.js:22:18)
   at Package (<runJavaScript-55>:55:7)


=> Your application has errors. Waiting for file change.
```

This did not present itself as an issue until the Meteor 1.0.4 upgrade.

After removing the package, and reinstalling the default `meteor add less`, I saw a different bug -- turns out, I was using a @lessVar in the file it was trying to compile, navbar.less, but I hadn't included the .less file that defined the variable!  So this error, `cannot read property css of undefined,` was being thrown for some reason due to the fact that the LESS compiler was really trying to say `Less compiler error: variable @navbarHeight is undefined.`

**Comment by flemay** [comment]
@msolters I have this issue when my nodejs environment is loaded. I retried in a docker container (which contains only meteor) and it does not show the error anymore. Same with my mac if I don't load nodejs. However my first problem persists still.

**Comment by msolters** [comment]
On what browsers?

**Comment by flemay** [comment]
Chrome

**Comment by msolters** [comment]
For OS X?

**Comment by flemay** [comment]
Yes. But I don't think it is a browser issue because it looks like my less files are not getting compiled when too many `@import (multiple)`

**Comment by msolters** [comment]
I agree with you.

**Comment by flemay** [comment]
Trying to reproduce the bug with his test but I noticed his test is not calling his plugin but relies on 'less' package.
